export const SHOW_POPUP = 'SHOW_POPUP'
export const SET_POPUP_TEXT = 'SET_POPUP_TEXT'


export const GET_DATA = 'GET_DATA'
export const SET_DATA = 'SET_DATA'

export const SET_CATEGORIES = 'SET_CATEGORIES'

export const SET_ELECTRONICS = 'SET_ELECTRONICS'
export const SET_JEWELERY = 'SET_JEWELERY'
export const SET_MEN_CLOTHING = 'SET_MEN_CLOTHING'
export const SET_WOMEN_CLOTHING = 'SET_WOMEN_CLOTHING'

export const SET_SELECTED_RATE_PRODUCTS = 'SET_SELECTED_RATE_PRODUCTS'
export const SET_ACTIVE_RATE = 'SET_ACTIVE_RATE'


export const SET_LOCATION = 'SET_LOCATION'


export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const INCREMENT_IN_CART = 'INCREMENT_IN_CART'
export const DECREMENT_IN_CART = 'DECREMENT_IN_CART'
export const ON_HAND_CHANGE_IN_CART = 'ON_HAND_CHANGE_IN_CART'
export const CLEAN_UP_CART = 'CLEAN_UP_CART'